git:
  submodules: false
matrix:
    include:
      - language: python
        dist: xenial
        python: '3.6'
        install:
            - pip install -r requirements.txt
            - python setup.py install
            - docker pull ewatercycle/walrus-grpc4bmi:v0.3.1
            - singularity pull docker://ewatercycle/walrus-grpc4bmi:v0.3.1
        script:
            - pytest --cov=grpc4bmi --cov-report xml
        cache:
         - pip
         - directories:
             - /usr/local
             - ~/.singularity
        services:
          - docker
        before_install:
          # Build singularity binary
          - |
              if [[ ! -f /usr/local/bin/singularity ]]; then
                sudo apt-get update
                sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev libseccomp-dev pkg-config squashfs-tools
                wget -O /tmp/go1.12.linux-amd64.tar.gz https://dl.google.com/go/go1.12.linux-amd64.tar.gz
                sudo tar -C /usr/local -xzf /tmp/go1.12.linux-amd64.tar.gz
                export GOPATH=~/go
                export PATH=$PATH:/usr/local/go/bin
                mkdir -p ~/go/src/github.com/sylabs
                cd ~/go/src/github.com/sylabs && \
                git clone https://github.com/sylabs/singularity.git && \
                cd singularity
                git checkout v3.1.0
                ./mconfig && \
                cd ./builddir && \
                make && \
                sudo make install
                cd ${TRAVIS_BUILD_DIR}
              fi
        after_success:
          - sonar-scanner -Dsonar.login=$SONAR_TOKEN
      - language: cpp
        before_install:
            - git submodule update --init
            - sudo apt-get update
            - sudo apt-get install -y build-essential autoconf libtool pkg-config libunwind-dev
            - | 
                if [[ ! -f /usr/local/bin/protoc || ! -f /usr/local/bin/grpc_cpp_plugin ]]; then
                  git clone -b v1.27.2 https://github.com/grpc/grpc
                  cd grpc
                  git submodule update --init --recursive
                  wget -q -O cmake-linux.sh https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5-Linux-x86_64.sh
                  sudo sh cmake-linux.sh -- --skip-license --prefix=/usr/local
                  rm cmake-linux.sh
                  mkdir cmake/build
                  cd cmake/build
                  /usr/local/bin/cmake ../.. -DgRPC_INSTALL=ON -DgRPC_SSL_PROVIDER=package -DgRPC_BUILD_TESTS=OFF
                  sudo make -j4 install
                  cd ${TRAVIS_BUILD_DIR}
                else
                  echo "using cached builds of protobuf and grpc"
                fi
        script:
            - mkdir -p ${TRAVIS_BUILD_DIR}/cpp/build && cd ${TRAVIS_BUILD_DIR}/cpp/build
            - /usr/local/bin/cmake ..
            - make
            - ctest -V
        cache:
            directories:
                - /usr/local
addons:
  sonarcloud:
    organization: ewatercycle

