# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: grpc4bmi/bmi.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import grpc4bmi.bmi_pb2


class BmiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def initialize(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.InitializeRequest, grpc4bmi.bmi_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def update(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def updateUntil(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.UpdateUntilRequest, grpc4bmi.bmi_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def updateFrac(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.UpdateFracRequest, grpc4bmi.bmi_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def finalize(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def getComponentName(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.GetComponentNameResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getInputVarNames(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.GetVarNamesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getOutputVarNames(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.GetVarNamesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getTimeUnits(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.GetTimeUnitsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getTimeStep(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.GetTimeStepResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getCurrentTime(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.GetTimeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getStartTime(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.GetTimeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getEndTime(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.Empty, grpc4bmi.bmi_pb2.GetTimeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getVarGrid(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GetVarRequest, grpc4bmi.bmi_pb2.GetVarGridResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getVarType(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GetVarRequest, grpc4bmi.bmi_pb2.GetVarTypeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getVarItemSize(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GetVarRequest, grpc4bmi.bmi_pb2.GetVarItemSizeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getVarUnits(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GetVarRequest, grpc4bmi.bmi_pb2.GetVarUnitsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getVarNBytes(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GetVarRequest, grpc4bmi.bmi_pb2.GetVarNBytesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getValue(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GetVarRequest, grpc4bmi.bmi_pb2.GetValueResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getValueAtIndices(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GetValueAtIndicesRequest, grpc4bmi.bmi_pb2.GetValueAtIndicesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def setValue(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.SetValueRequest, grpc4bmi.bmi_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def setValueAtIndices(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.SetValueAtIndicesRequest, grpc4bmi.bmi_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def getGridSize(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridSizeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridType(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridTypeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridRank(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridRankResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridShape(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridShapeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridSpacing(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridSpacingResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridOrigin(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridOriginResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridX(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridPointsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridY(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridPointsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridZ(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridPointsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridConnectivity(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridConnectivityResponse]') -> None:
        pass

    @abc.abstractmethod
    async def getGridOffset(self, stream: 'grpclib.server.Stream[grpc4bmi.bmi_pb2.GridRequest, grpc4bmi.bmi_pb2.GetGridOffsetResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/bmi.BmiService/initialize': grpclib.const.Handler(
                self.initialize,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.InitializeRequest,
                grpc4bmi.bmi_pb2.Empty,
            ),
            '/bmi.BmiService/update': grpclib.const.Handler(
                self.update,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.Empty,
            ),
            '/bmi.BmiService/updateUntil': grpclib.const.Handler(
                self.updateUntil,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.UpdateUntilRequest,
                grpc4bmi.bmi_pb2.Empty,
            ),
            '/bmi.BmiService/updateFrac': grpclib.const.Handler(
                self.updateFrac,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.UpdateFracRequest,
                grpc4bmi.bmi_pb2.Empty,
            ),
            '/bmi.BmiService/finalize': grpclib.const.Handler(
                self.finalize,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.Empty,
            ),
            '/bmi.BmiService/getComponentName': grpclib.const.Handler(
                self.getComponentName,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.GetComponentNameResponse,
            ),
            '/bmi.BmiService/getInputVarNames': grpclib.const.Handler(
                self.getInputVarNames,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.GetVarNamesResponse,
            ),
            '/bmi.BmiService/getOutputVarNames': grpclib.const.Handler(
                self.getOutputVarNames,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.GetVarNamesResponse,
            ),
            '/bmi.BmiService/getTimeUnits': grpclib.const.Handler(
                self.getTimeUnits,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.GetTimeUnitsResponse,
            ),
            '/bmi.BmiService/getTimeStep': grpclib.const.Handler(
                self.getTimeStep,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.GetTimeStepResponse,
            ),
            '/bmi.BmiService/getCurrentTime': grpclib.const.Handler(
                self.getCurrentTime,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.GetTimeResponse,
            ),
            '/bmi.BmiService/getStartTime': grpclib.const.Handler(
                self.getStartTime,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.GetTimeResponse,
            ),
            '/bmi.BmiService/getEndTime': grpclib.const.Handler(
                self.getEndTime,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.Empty,
                grpc4bmi.bmi_pb2.GetTimeResponse,
            ),
            '/bmi.BmiService/getVarGrid': grpclib.const.Handler(
                self.getVarGrid,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GetVarRequest,
                grpc4bmi.bmi_pb2.GetVarGridResponse,
            ),
            '/bmi.BmiService/getVarType': grpclib.const.Handler(
                self.getVarType,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GetVarRequest,
                grpc4bmi.bmi_pb2.GetVarTypeResponse,
            ),
            '/bmi.BmiService/getVarItemSize': grpclib.const.Handler(
                self.getVarItemSize,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GetVarRequest,
                grpc4bmi.bmi_pb2.GetVarItemSizeResponse,
            ),
            '/bmi.BmiService/getVarUnits': grpclib.const.Handler(
                self.getVarUnits,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GetVarRequest,
                grpc4bmi.bmi_pb2.GetVarUnitsResponse,
            ),
            '/bmi.BmiService/getVarNBytes': grpclib.const.Handler(
                self.getVarNBytes,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GetVarRequest,
                grpc4bmi.bmi_pb2.GetVarNBytesResponse,
            ),
            '/bmi.BmiService/getValue': grpclib.const.Handler(
                self.getValue,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GetVarRequest,
                grpc4bmi.bmi_pb2.GetValueResponse,
            ),
            '/bmi.BmiService/getValueAtIndices': grpclib.const.Handler(
                self.getValueAtIndices,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GetValueAtIndicesRequest,
                grpc4bmi.bmi_pb2.GetValueAtIndicesResponse,
            ),
            '/bmi.BmiService/setValue': grpclib.const.Handler(
                self.setValue,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.SetValueRequest,
                grpc4bmi.bmi_pb2.Empty,
            ),
            '/bmi.BmiService/setValueAtIndices': grpclib.const.Handler(
                self.setValueAtIndices,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.SetValueAtIndicesRequest,
                grpc4bmi.bmi_pb2.Empty,
            ),
            '/bmi.BmiService/getGridSize': grpclib.const.Handler(
                self.getGridSize,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridSizeResponse,
            ),
            '/bmi.BmiService/getGridType': grpclib.const.Handler(
                self.getGridType,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridTypeResponse,
            ),
            '/bmi.BmiService/getGridRank': grpclib.const.Handler(
                self.getGridRank,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridRankResponse,
            ),
            '/bmi.BmiService/getGridShape': grpclib.const.Handler(
                self.getGridShape,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridShapeResponse,
            ),
            '/bmi.BmiService/getGridSpacing': grpclib.const.Handler(
                self.getGridSpacing,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridSpacingResponse,
            ),
            '/bmi.BmiService/getGridOrigin': grpclib.const.Handler(
                self.getGridOrigin,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridOriginResponse,
            ),
            '/bmi.BmiService/getGridX': grpclib.const.Handler(
                self.getGridX,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridPointsResponse,
            ),
            '/bmi.BmiService/getGridY': grpclib.const.Handler(
                self.getGridY,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridPointsResponse,
            ),
            '/bmi.BmiService/getGridZ': grpclib.const.Handler(
                self.getGridZ,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridPointsResponse,
            ),
            '/bmi.BmiService/getGridConnectivity': grpclib.const.Handler(
                self.getGridConnectivity,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridConnectivityResponse,
            ),
            '/bmi.BmiService/getGridOffset': grpclib.const.Handler(
                self.getGridOffset,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc4bmi.bmi_pb2.GridRequest,
                grpc4bmi.bmi_pb2.GetGridOffsetResponse,
            ),
        }


class BmiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.initialize = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/initialize',
            grpc4bmi.bmi_pb2.InitializeRequest,
            grpc4bmi.bmi_pb2.Empty,
        )
        self.update = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/update',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.Empty,
        )
        self.updateUntil = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/updateUntil',
            grpc4bmi.bmi_pb2.UpdateUntilRequest,
            grpc4bmi.bmi_pb2.Empty,
        )
        self.updateFrac = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/updateFrac',
            grpc4bmi.bmi_pb2.UpdateFracRequest,
            grpc4bmi.bmi_pb2.Empty,
        )
        self.finalize = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/finalize',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.Empty,
        )
        self.getComponentName = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getComponentName',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.GetComponentNameResponse,
        )
        self.getInputVarNames = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getInputVarNames',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.GetVarNamesResponse,
        )
        self.getOutputVarNames = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getOutputVarNames',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.GetVarNamesResponse,
        )
        self.getTimeUnits = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getTimeUnits',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.GetTimeUnitsResponse,
        )
        self.getTimeStep = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getTimeStep',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.GetTimeStepResponse,
        )
        self.getCurrentTime = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getCurrentTime',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.GetTimeResponse,
        )
        self.getStartTime = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getStartTime',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.GetTimeResponse,
        )
        self.getEndTime = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getEndTime',
            grpc4bmi.bmi_pb2.Empty,
            grpc4bmi.bmi_pb2.GetTimeResponse,
        )
        self.getVarGrid = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getVarGrid',
            grpc4bmi.bmi_pb2.GetVarRequest,
            grpc4bmi.bmi_pb2.GetVarGridResponse,
        )
        self.getVarType = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getVarType',
            grpc4bmi.bmi_pb2.GetVarRequest,
            grpc4bmi.bmi_pb2.GetVarTypeResponse,
        )
        self.getVarItemSize = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getVarItemSize',
            grpc4bmi.bmi_pb2.GetVarRequest,
            grpc4bmi.bmi_pb2.GetVarItemSizeResponse,
        )
        self.getVarUnits = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getVarUnits',
            grpc4bmi.bmi_pb2.GetVarRequest,
            grpc4bmi.bmi_pb2.GetVarUnitsResponse,
        )
        self.getVarNBytes = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getVarNBytes',
            grpc4bmi.bmi_pb2.GetVarRequest,
            grpc4bmi.bmi_pb2.GetVarNBytesResponse,
        )
        self.getValue = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getValue',
            grpc4bmi.bmi_pb2.GetVarRequest,
            grpc4bmi.bmi_pb2.GetValueResponse,
        )
        self.getValueAtIndices = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getValueAtIndices',
            grpc4bmi.bmi_pb2.GetValueAtIndicesRequest,
            grpc4bmi.bmi_pb2.GetValueAtIndicesResponse,
        )
        self.setValue = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/setValue',
            grpc4bmi.bmi_pb2.SetValueRequest,
            grpc4bmi.bmi_pb2.Empty,
        )
        self.setValueAtIndices = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/setValueAtIndices',
            grpc4bmi.bmi_pb2.SetValueAtIndicesRequest,
            grpc4bmi.bmi_pb2.Empty,
        )
        self.getGridSize = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridSize',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridSizeResponse,
        )
        self.getGridType = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridType',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridTypeResponse,
        )
        self.getGridRank = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridRank',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridRankResponse,
        )
        self.getGridShape = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridShape',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridShapeResponse,
        )
        self.getGridSpacing = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridSpacing',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridSpacingResponse,
        )
        self.getGridOrigin = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridOrigin',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridOriginResponse,
        )
        self.getGridX = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridX',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridPointsResponse,
        )
        self.getGridY = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridY',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridPointsResponse,
        )
        self.getGridZ = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridZ',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridPointsResponse,
        )
        self.getGridConnectivity = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridConnectivity',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridConnectivityResponse,
        )
        self.getGridOffset = grpclib.client.UnaryUnaryMethod(
            channel,
            '/bmi.BmiService/getGridOffset',
            grpc4bmi.bmi_pb2.GridRequest,
            grpc4bmi.bmi_pb2.GetGridOffsetResponse,
        )
